name: Linux arm64

on:
  push:
    branches: [test/linux-arm64]

env:
  #LD_DEBUG: symbols
  DOTNET_EnableWriteXorExecute: 0

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: uraimo/run-on-arch-action@v2
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04

          run: |
            apt-get update && apt-get install -y curl unzip libsnappy-dev dotnet-sdk-7.0 git
            #curl -sL https://globalcdn.int.nugettest.org/packages/nethermind.crypto.secp256k1.1.0.0-preview.8.nupkg -o neth.zip
            #curl -sL https://github.com/NethermindEth/nethermind/releases/download/1.19.0-rc/nethermind-1.19.0-rc-d8765075-linux-arm64.zip -o neth.zip
            #mkdir neth
            #unzip neth.zip -d neth
            #ldd neth/runtimes/linux-arm64/native/libsecp256k1.so
            git clone --single-branch --branch test/linux-arm64 https://github.com/nethermindeth/nethermind
            cd nethermind/src/Nethermind/Nethermind.Runner
            dotnet build -c release
            dotnet run -c release -- -c sepolia
            #./Nethermind.Runner -c sepolia &
            #sleep 10m

      
