name: Linux arm64

on:
  push:
    branches: [test/linux-arm64]

#env:
#  LD_DEBUG: symbols    

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: uraimo/run-on-arch-action@v2
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu_latest

          run: |
            apt-get update && apt-get install -y curl unzip libsnappy-dev libgflags-dev -y
            curl -sL https://globalcdn.nuget.org/packages/nethermind.crypto.secp256k1.1.0.0.nupkg -o neth.zip
            #curl -sL https://github.com/NethermindEth/nethermind/releases/download/1.19.0-rc/nethermind-1.19.0-rc-d8765075-linux-arm64.zip -o neth.zip
            mkdir neth
            unzip neth.zip -d neth
            ldd neth/runtimes/linux-x64/native/libsecp256k1.so
            #./Nethermind.Runner -c sepolia &
            sleep 40s

      
